# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test backend

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.6.1
      - name: Install dependencies
        working-directory: .
        run: |
          poetry install
      - name: Lint with ruff
        working-directory: .
        run: |
          poetry run ruff check .
          poetry run ruff format --check .
      - name: Run mypy
        working-directory: .
        run: |
          poetry run mypy
      - name: Run pytest
        working-directory: .
        run: |
          poetry run pytest test_flask
          poetry run pytest test_api
